config/routes.rb
Ticketee::Application.routes.draw do
  devise_for :users

  # When / is received the root route is called. 
  # We say that when root route is called we will point to ProjectController's Index action.
  # We use the "root" method to specify the root route
  root :to => "projects#index"

  # A resource route is basically a collection/bundle of all routes for a given resource.
  # It is like a package of all routes that gets applied on the mentioned resource.
  # We use the "resources" method to add a resource in the route table
  # A resource route also makes helper functions available to us i.e it creates an alias
  # for each route 
  # Eg: If you do rake routes... you see  
  # projects GET  "/projects" projects#index
  # this means that this route will match the url of type http://xyz.com/projects
  # this route will call index action in projects controller when matched
  # this route has been named an alias "projects". (i.e the value in first column before GET)  
  # It is similiar to writing GET "/projects", projects#index, as:projects (Ref:http://guides.rubyonrails.org/routing.html)
  # Due to this alias two helper functions also becomes available for generating the url's whenever required.
  # i.e alias_path for generating the relative url and alias_url for generating the absolute path.(Ref: Rails 3 in Action)
  # Hence in case of alias new_project we get two helpers viz. 
  # new_project_path which will generate '/project' (relative url) and
  # new_project_url which will generate 'http://xyz.com/project' (absolute url)

  resources :projects do
  	resources :tickets
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name

  has_many :tickets

  validates :name, presence:true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project

  validates :title, presence:true
  validates :description, presence:true,
  	                      :length => {:minimum => 10}

  attr_accessible :description, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	# By default before_filters are run\called before all the actions of project controller.
	# However this can be controlled by using :only or :except options.
	# :only can be used to mention actions before which the filter should be called.
	# :except can be used to mention actions before which the filter should not be called.
	before_filter :find_project, :only => [	:show,
											:edit,
											:update,
											:destroy]

	def index
		@projects = Project.all
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(params[:project])
		if @project.save
			flash[:notice] = "Project has been created."
			redirect_to @project
		else
			flash[:alert] = "Project has not been created."
			render :action => "new"
		end
	end

	def show
		# commenting out as this line is being handelled by before_filter
		# @project = Project.find(params[:id])
	end

	def edit
		# commenting out as this line is being handelled by before_filter
		# @project = Project.find(params[:id])
	end

	def update
		# commenting out as this line is being handelled by before_filter
		# @project = Project.find(params[:id])

		# update the table records with whatever has changed in params[:project] 
		if @project.update_attributes(params[:project])  
			flash[:notice] = "Project has been updated."
			redirect_to @project
		else
			flash[:alert] = "Project has not been updated."
			render :action => "edit"
		end
	end

	def destroy
		# commenting out as this line is being handelled by before_filter
		# project = Project.find(params[:id])
		@project.destroy
		flash[:notice] = "Project has been deleted."
		redirect_to projects_path
	end

	private   # As this method has private method before it, the controller cannot respond to this 
			  #	method as an action. i.e nobody can call this method. 
		def find_project
			@project = Project.find(params[:id])
			rescue ActiveRecord::RecordNotFound
				flash[:alert] = "The project you were looking for could not be found."	 
			redirect_to projects_path
		end
end


# Question: When is id passed and when is the entire project passed in the params[]

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
	before_filter :find_project # no options are required as in case of ticket this method has to 
								# run before all the actions in TicketController.  

	before_filter :find_ticket, :only => [	:show, 
										  	:edit,
											:update, 
											:destroy]

	def new
		@ticket = @project.tickets.build
	end

	def create
		@ticket = @project.tickets.build(params[:ticket])
		if @ticket.save
			flash[:notice] = "Ticket has been created."
			redirect_to [@project, @ticket]  # => same as calling redirect_to project_ticket_path(@project, @ticket)
		else
			flash[:alert] = "Ticket has not been created."
			render :action => "new"
		end 
	end

	def show
	end

	def edit 
	end

	def update
		# @ticket and @project are already being obtained in the before_filter, so no need to find them.
		if @ticket.update_attributes(params[:ticket])
			flash[:notice] = "Ticket has been updated."
			redirect_to project_ticket_path(@project, @ticket)
		else
			flash[:alert] = "Ticket has not been updated."
			render :action => "edit"
		end
	end

	def destroy
		@ticket.destroy()
		flash[:notice] = "Ticket has been deleted."
		redirect_to @project  # => same as calling redirect_to project_path(@project) i.e the show action.
	end

	private 
	def find_project
		@project = Project.find(params[:project_id])
	end

	def find_ticket
		@ticket = @project.tickets.find(params[:id])
	end
end


# render if you want to maintain/retain the instance objects and display the page.
# redirect if you do not want to maintain the object and display a fresh page(i.e without any current object information).

app/helpers/application_helper.rb
module ApplicationHelper
	def title(*parts)
		# if title is called with some aruments then go ahead and create a title tag with the argument as it content.
		unless parts.empty?
			#create content block for title tag. Going ahead we will render this content block using yield.
			content_for :title do 
				(parts << "Ticketee").join(" - ") unless parts.empty? 
			end 
		end
	end
end

#Our aim is to remove the title setting logic from show.html and move it to helper.

# Here we create a title tag using the content_for function, with the arguments passed to the title helper function. 

# In show,html.erb(which is a template) we call this helper function and pass the project name and "Projects" string.

# In application.html.erb(which is a layout), we check if the title tag is already defined by using the 
# content_for? function. (content_for :title defines a content for title tag and content_for? checks if 
# content for title tag is # defined). 
# Now as templates are executed before layouts (i.e all function calls, variables. content blocks etc are 
# already executed and kept before calling layouts), content_for? is true and then we call a yield and 
# pass it the name of the content block, which causes the content for that block to be rendered.
# (Ref: Rails 3 in Action: Pg 76)

# What are content blocks?
# Find and add here.

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><% if content_for? (:title) %><%=yield(:title)%><% else %><%= "Ticketee" %><% end %></title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<% flash.each do |key, value| %>
	<div class='flash' id='<%= key %>'>
		<%= value %>
	</div>	
<% end %> 

<h1><%= link_to "Ticketee", root_path %></h1>

<div>
	<%= link_to "Sign up", new_user_registration_path %>
</div>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
	 <!-- This dynamic_form gem method shows the rails generated model errors at the position where it is placed. -->
	 <%= f.error_messages %>
	 
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
		<%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<%= render "form" %>

app/views/projects/index.html.erb
<%= link_to "New Project", new_project_path %>

<h2>Projects</h2>
<ul>
	<% @projects.each do |project| %>
		<li><%= link_to project.name, project_path(project)%><li>
	<% end %>
</ul>

app/views/projects/new.html.erb
<h2> New Project </h2>
<%= render "form" %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %> 

<%= link_to "Edit Project", edit_project_path(@project) %>

<%= link_to "Delete Project", project_path(@project), :method => :delete %> 

<%= link_to "New Ticket", new_project_ticket_path(@project) %>

<ul id="tickets">
	<% @project.tickets.each do |ticket| %>
		<li>
			<%= ticket.id %> - <%= link_to ticket.title, project_ticket_path(@project, ticket)	%>
		</li>
	<% end %>	
</ul>

app/views/tickets/_form.html.erb
<%= form_for([@project, @ticket]) do |f| %>
	<%= f.error_messages %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</p>
	<%= f.submit %>
<% end %>

app/views/tickets/edit.html.erb
<h2>Edit Ticket</h2>
<%= render "form" %>

app/views/tickets/new.html.erb
<h2> New Ticket </h2>
<%= render "form" %>

app/views/tickets/show.html.erb
<div id="ticket">
	<h2><%= @ticket.title %></h2>
	<%= link_to "Edit Ticket", edit_project_ticket_path(@project, @ticket)%>
	<%= link_to "Delete Ticket", 	project_ticket_path(@project, @ticket), 	
									:method => :delete,
									:confirm => "Are you sure you want to delete this ticket?" %>


	<%= simple_format(@ticket.description) %>
</div>